### ISSUE TITLE
0.139.0: undefined local variable or method 'tag_list' for an instance of Scan::Model::ParseMetadataJob

### ISSUE THREAD

**Issue by binderth** [manyfold3d/manyfold#6059]
**Describe the bug**
After upgrading to 0.139.0 (9dcfa3fe), the use of the API doesn't work anymore. the process stops after throwing the error:
`undefined local variable or method 'tag_list' for an instance of Scan::Model::ParseMetadataJob`

**To Reproduce**
1. create a zip with all the STLs, JPGs, ...
2. create a datapackage.json containing tags for the model
3. use API to add the model

**Expected behavior**
uploading a model with the contents of the datapackage.json including tags leads to a new model with all information placed

**Screenshots**
log entries:

<details><summary>log entries of import</summary>

| name | when |  message | 
| ------------- | ------------- |  ------------- | 
| Scan::Model::CheckForProblemsJob | weniger als eine Minute |  |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::GeometricAnalysisJob | weniger als eine Minute |   |
| Scan::Model::CheckForProblemsJob | weniger als eine Minute |   |
| Analysis::GeometricAnalysisJob | weniger als eine Minute |   |
| UpdateDatapackageJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Analysis::AnalyseModelFileJob | weniger als eine Minute |   |
| Scan::Model::ParseMetadataJob | weniger als eine Minute | undefined local variable or method 'tag_list' for instance of Scan::Model::ParseMetadataJob |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::Model::AddNewFilesJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |   |
| ProcessUploadedFileJob | weniger als eine Minute |   |
| Scan::ModelFile::ParseMetadataJob | weniger als eine Minute |  |

</details>

[logfile.txt](https://github.com/user-attachments/files/27467119/logfile.txt)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
same API-calls did work with last version 0.138.0 (see my https://github.com/manyfold3d/manyfold/discussions/5859 )

**Comment by Floppy** [comment]
Thank you, this will be causing problems with all datapackages. I'll get it fixed asap.

**Comment by Floppy** [comment]
Thanks for finding this - a fix is now released in v0.139.1
